### ISSUE TITLE
ns_ttl.c won't compile with clang-900.0.38

### ISSUE THREAD

**Issue by djw1149** [dnsdb/dnsdb_c#8]
```
cc -g -W -Wall -Wcast-qual -Wpointer-arith -Wwrite-strings -Wmissing-prototypes  -Wbad-function-cast -Wnested-externs -Wunused -Wshadow -Wmissing-noreturn -Wswitch-enum -Wformat-nonliteral -Werror `curl-config --cflags`  -I/usr/local/include -c ns_ttl.c
ns_ttl.c:54:24: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                case 'W':  tmp *= 7; __attribute__ ((fallthrough));
                                     ^
ns_ttl.c:55:25: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                case 'D':  tmp *= 24; __attribute__ ((fallthrough));
                                      ^
ns_ttl.c:56:25: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                case 'H':  tmp *= 60; __attribute__ ((fallthrough));
                                      ^
ns_ttl.c:57:25: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                case 'M':  tmp *= 60; __attribute__ ((fallthrough));
                                      ^
```
A solution was to comment out the \_\_attribute\_\_ half of those four lines.

**Comment by vixie** [comment]
fixed in commit a3fea9750b2f0c25f144477229dd3bcd4e645381

**Comment by vixie** [comment]
still won't compile on debian 9.

**Comment by vixie** [comment]
new fix, commit 3f87633b818c0402c42583f7d7915c17b2d55aee
